[build]
  base = "."
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/build"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://chad-foundation.netlify.app/*"
  to = "https://chad-foundation.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  targetPort = 3000
  port = 8888
  framework = "#custom"
  autoLaunch = true